// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db_modles

var TableNames = struct {
	Orders string
}{
	Orders: "orders",
}
